config/routes.rb
BlendMarks::Application.routes.draw do
  get "error/index"
  get "coming/index"
  match "login", :controller => "user_sessions", :action => "new"
  match "logout", :controller => "user_sessions", :action => "destroy"
  match "register", :controller => "users", :action => "new"
  match "error", :controller => "error", :action => "index"
  match 'forgotpassword', :controller => "users", :action => "forgotpassword"
  match 'resetpassword/:id', :controller => "users", :action => "resetpassword"
  match 'quickentry', :controller => "links", :action => "quickentry"
  match 'addlink', :controller => "links", :action => "create"
  match 'confirminvitation', :controller => "users", :action => "confirminvitation"
  match 'addtag', :controller => "links", :action => "addtag"
  match 'readmail', :controller => "links", :action => "readlinksfrommail"
  match 'sendnotification',:controller => "links" , :action => "sendnotification"
  match "subscribe", :controller => "coming", :action => "subscribe"
  match 'search/:criteria(/:pageindex)', :controller => "links", :action => "search"
  match '/', :controller => "links", :action => "index" , :constraints => {:subdomain => "blendmarks"}
  match '/', :controller => "coming", :action => "index"
  match 'links/index(/:pageindex)', :controller => "links", :action => "index"
  match ':controller/:action(/:id)'
  match ':controller/:action'
  match 'tag/:tag(/:pageindex)', :controller => "links", :action => "tagfilter"
  match '/autocomplete', :controller => "links", :action => "tagautocomplete"
  resources :links
  resource :users
  resources :coming
  resources :user_sessions
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  acts_as_authentic
  belongs_to :link
  belongs_to :group
  validates_presence_of :username, :email, :group_id
  validates_format_of :email, :with => %r{^(?:[_a-z0-9|+-]+)(\.[_a-z0-9|+-]+)*@([a-z0-9-]+)(\.[a-zA-Z0-9\-\.]>> +)*(\.[a-z]{2,4})$}i, :message => "invalid email format."
  validates_uniqueness_of :username, :email
  before_save :setbookmartletcode

  def send_reset_password
    reset_code = User.random_string(10)
    self.reset_code = reset_code
    self.save
    UserMailer.deliver_forgot_password(self, reset_code)
  end

  def send_invitation
    reset_code = User.random_string(10)
    self.reset_code = reset_code
    self.save
    UserMailer.deliver_invitation(self, reset_code,self.group.title)
  end

  protected
  def self.random_string(len)
    #generat a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end

  def setbookmartletcode
      self.bookmarkletcode = User.random_string(10)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter "setsubdomainasgroup"
  before_filter "isuserloggedin", :only =>["edit", "update","destroy", "invitepeople", "confirminvitation"]

  def new
    @user = User.new
  end

  def create
    unless params[:user].nil?
      @user = User.new(params[:user])
      @user.username = @user.email
      @user.isnotificationsubscribed = true
      @user.group_id = session[:group]
      @user.bookmarkletcode = User.random_string(10)
      if @user.save
        flash[:notice] = 'Registration successfully completed.'
        redirect_to :controller => "links", :action => "index"
      else
        flash[:notice] = "Invalid parameter values passed."
        #puts @user.errors.full_messages
        render :action => "new"
      end
    else
      flash[:notice] = 'user credentials not passed.'
      render :action => "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    unless params[:user].nil?
      @user = current_user
      if @user.update_attributes(params[:user])
        flash[:notice] = 'Your profile updated successfully.'
        redirect_to :controller => "links", :action => "index"
      else
        #puts @user.errors.full_messages
        flash[:notice] = 'Invalid parameters passed.'
        render :action => "edit"
      end
    else
      flash[:notice] = 'User credentials not passed.'
      edit
      render :edit
    end
  end

  def forgotpassword
    unless params[:username].nil?
      user = User.find_by_username(params[:username].to_s)
      unless user.nil?
        @error = nil
        user.send_reset_password
        @status = "An email has been sent to you for resetting your password."
        render :success
      else
        @error = 'Invalid email address entered!'
      end
    end
  end

  def success
    @status = ""
  end

  def resetpassword
    unless params[:id].nil?
      @user = User.where(:reset_code => params[:id]).first
      if @user.nil?
        redirect_to :controller => "error", :action => "index"
      end
    else
      redirect_to :controller => "error", :action => "index"
    end
  end

  def setpassword
    unless params[:username].nil?
      unless params[:password].nil?
        unless params[:confirm_password].nil?
          unless params[:password].to_s != params[:confirm_password]
            @user = User.find_by_username(params[:username])
            @user.password = params[:password]
            @user.password_confirmation = params[:password]
            if @user.save
              @status = "Your password has been modified."
            else
              @status = "Oops! We are unable to set your password."
            end
            render :success
            return
          end
        end
      end
      @user = User.find_by_username(params[:username])
      render :resetpassword
    else
      redirect_to :controller => "error", :action => "index"
    end
  end

  def destroy
    unless params[:id].nil?
      @user = User.find_by_id(params[:id])
      unless @user.nil?
        @user.destroy
      end
      redirect_to :controller => "links", :action => "index"
    else
      redirect_to error_url
    end
  end

  def invitepeople
     @user = User.new
     render :layouts=> false
  end

  def confirminvitation
    unless params[:email].nil?
      email = params[:email]
      email.split("\n").each do |mail|
        mail.split(";").each do |m|
          user = User.new
          user.group_id = session[:group]
          user.bookmarkletcode = User.random_string(10)
          user.email = m
          password = User.random_string(10)
          user.password = password
          user.password_confirmation = password
          user.username =   m
          user.isnotificationsubscribed=true
          if user.save
            user.send_invitation
          else
            puts "error at saving user due to " + user.errors.full_messages[0]
          end 
        end
      end
      render :text => "success"
    else
      render :text => "invalid parameters passed."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/forgotpassword.html.erb
<div id="login-box-container">
    <div id="center">
        <%= image_tag "logo.png" %>
        <div id="login-box" class="WarpShadow WLarge WLight">
          <div class="forgot-password-information">
            <h4>Did you forget your password?</h4>
            <p>Enter your email address below and we'll send you your password reset instructions.</p>
          </div>
            <%= form_tag(:action => "forgotpassword")  do |f| %>
                <% if @error.nil? %>
                <% else %>
                  <div class="alert-error">
                    Please enter a valid email address.
                  </div>
                <% end %>
            <fieldset>
                <label>Enter your email address</label>
                <input type="text" class="small" name="username" maxlength="100" />
            </fieldset>
              <span class="menu-button"><a href="#" onclick="document.forms[0].submit();" class="css3-button">Email password reset instructions</a></span>
            <% end %>
        </div>
    </div>
</div>

app/views/users/invitepeople.html.erb
<div class="add-link-form">
    <%= form_tag("/confirminvitation") do |f| -%>
        <div class="clearfix errorbox">
        </div>
        <label>Email</label>
        <textarea class="small" name="email" ></textarea>
        <%= link_to 'Send invitation', "#", :class => "css3-button btnsendinvitation" -%>
    <% end -%>
</div>

<%= javascript_include_tag "JQValidation" %>

app/views/users/new.html.erb
<div id="login-box-container">
    <div id="center">
        <%= image_tag "logo.png" %>
        <div id="login-box">
       <%= form_for(@user) do |f| %>
            <h1>Register</h1>
            <% if @user.errors.any? %>
                <div class="alert-error">
                    <p><%= @user.errors.full_messages[0] %></p>
                </div>
            <% end %>
            <!-- Add class="error-fieldset" to the fieldset tag in case there is an error, this class has to be added to any fieldset that has an error -->
            <fieldset>
                <label>Email</label>
                  <%= f.text_field :email, :class => "small" %>
                <!-- Message to be shown below the filed which has a problem
                <p>Improper email format</p>
                -->
            </fieldset>
            <fieldset>
                <label>Password</label>
                <%= f.password_field :password, :class => "small" %>
            </fieldset>
            <fieldset>
                <label>Confirm Password</label>
                <%= f.password_field :password_confirmation, :class => "small" %>
            </fieldset>
            <fieldset>
                <%= link_to 'Register', "#", :id => "BtnFormSubmit" ,:class => "css3-button" -%>
            </fieldset>
            <p class="forgot-password">Did you <%= link_to "forget your password?", :action => "forgotpassword" %> or do you need to <%= link_to 'login.', login_url  -%></p>
        <% end %>
        </div>
    </div>
</div>

app/views/users/resetpassword.html.erb
<div id="login-box-container">
    <div id="center">
        <%= image_tag "logo.png" %>
        <div id="login-box">
            <h1>Reset your password</h1>
            <%= form_tag(:action => "setpassword")  do |f| %>
                <% unless @error.nil? %>
                <div class="error">
                    <p><%= @error %></p>
                </div>
              <% end %>
            <fieldset>
                <label>Password</label>
                <input type="hidden" name="username" value="<%= @user.username %>" >
                <input type="password" class="login-text" name="password" maxlength="15" />
            </fieldset>
            <fieldset>
                <label>Confirm Password</label>
                <input type="password" class="login-text" name="confirm_password" maxlength="15" />
            </fieldset>
            <fieldset>
                 <span class="menu-button"><a href="#" onclick="document.forms[0].submit();" class="css3-button">Reset my password</a></span>
            </fieldset>
              <% end %>
        </div>
    </div>
</div>

app/views/users/success.html.erb
<div id="login-box-container">
    <div id="center">
        <%= image_tag "logo.png" %>
        <div id="login-box" class="WarpShadow WLarge WLight">
		    <h1>Status!</h1>
            <fieldset>
                <p><%= @status %></p>
            </fieldset>
            <fieldset>
                <p>Or</p>
            </fieldset>
            <fieldset>
              <p>You can try again by clicking <%= link_to "here", :controller => "user_sessions", :action => "new" %> to login.</p>
            </fieldset>
        </div>
    </div>
</div>