config/routes.rb
BlendMarks::Application.routes.draw do
  get "error/index"
  get "coming/index"
  match "login", :controller => "user_sessions", :action => "new"
  match "logout", :controller => "user_sessions", :action => "destroy"
  match "register", :controller => "users", :action => "new"
  match "error", :controller => "error", :action => "index"
  match 'forgotpassword', :controller => "users", :action => "forgotpassword"
  match 'resetpassword/:id', :controller => "users", :action => "resetpassword"
  match 'quickentry', :controller => "links", :action => "quickentry"
  match 'addlink', :controller => "links", :action => "create"
  match 'confirminvitation', :controller => "users", :action => "confirminvitation"
  match 'addtag', :controller => "links", :action => "addtag"
  match 'readmail', :controller => "links", :action => "readlinksfrommail"
  match 'sendnotification',:controller => "links" , :action => "sendnotification"
  match "subscribe", :controller => "coming", :action => "subscribe"
  match 'search/:criteria(/:pageindex)', :controller => "links", :action => "search"
  match '/', :controller => "links", :action => "index" , :constraints => {:subdomain => "blendmarks"}
  match '/', :controller => "coming", :action => "index"
  match 'links/index(/:pageindex)', :controller => "links", :action => "index"
  match ':controller/:action(/:id)'
  match ':controller/:action'
  match 'tag/:tag(/:pageindex)', :controller => "links", :action => "tagfilter"
  match '/autocomplete', :controller => "links", :action => "tagautocomplete"
  resources :links
  resource :users
  resources :coming
  resources :user_sessions
end

app/models/link.rb
class Link < ActiveRecord::Base
    belongs_to :group
    has_many :tag
    has_one :user
    validates_presence_of :title, :link, :tag_id, :group_id, :user_id
    validates_uniqueness_of :link
    #validates_format_of :link, :with => '/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix'
    #before_save :sendnotification
    after_save :addnotification
  protected
  def sendnotification
    #dont add this method, it takes few time to send, so the user page interactions breaks
    #User.find(:all, :conditions => "isnotificationsubscribed = true").each do |user|
    #  UserMailer.deliver_urlnotiication(self,user)
    #end
  end
  def addnotification
    notification = Notificationlink.new
    notification.link = self.link
    notification.save
  end
end

app/controllers/links_controller.rb
require "mail"
require "indextank"
class LinksController < ApplicationController
  before_filter "isuserloggedin" , :except => [:quickentry]
  before_filter "setsubdomainasgroup"
  protect_from_forgery :except => [:addtag,:search,:readlinksfrommail,:quickentry]
  #verify :method => :get, :except => [:create,:update]
  #verify :method => :post, :only => [:create,:update]
  def index

    #flash[:notice] = "welcome to interesting links."
    if session[:id].nil?
      session[:id] = params[:id]
    end
    unless session[:id].nil?
      #puts session[:id]
      redirect_to :action => "new"
      return
    end
    noOfLinksperPage = ENV['NoOfLinksPerPage']
    noOfLinksSkipCount = 0
    unless params[:pageindex].nil? 
      noOfLinksSkipCount = noOfLinksperPage.to_i * params[:pageindex].to_i
    end
    if @pattern.nil?
       @links = Link.limit(noOfLinksperPage).offset(noOfLinksSkipCount).find(:all,:conditions => "group_id = '#{session[:group]}'", :order => "id desc")
    else
      tag = @tagsearch
      if tag == 0
        tag = 1
      end
       @links = Link.limit(noOfLinksperPage).offset(noOfLinksSkipCount).find(:all,:conditions => "group_id = '#{session[:group]}'", :order => "id desc") #Link.find(:all, :conditions => "(link ~* '#{@pattern}' or description ~* '#{@pattern}') and tag = '#{@tagsearch}'")
    end
    @tag = Tag.new
    
    @tags = {}
    Tag.all.each do |tag|
      @tags[tag.id] = tag.name
    end
    flash[:filter] = false
    unless params[:pageindex].nil?
       render :layout => false
    end

  end

  def search
    begin

      @criteria = params[:criteria]
      noOfLinksperPage = ENV['NoOfLinksPerPage']
      noOfLinksSkipCount = 0
      unless params[:pageindex].nil?
        noOfLinksSkipCount = noOfLinksperPage.to_i * params[:pageindex].to_i
      end

      # searching with the default text comparisons
      result = Link.find(:all, :conditions => "content like '%#{@criteria}%'")  #Yml.search_hash(@criteria)
      @links = []
      result.each do |res|
        @links.push(res)
      end

      # searching with Index Tank
      unless @criteria.nil?
        client = IndexTank::Client.new('http://:ZugDaAAC61N0k8@drxq3.api.indextank.com')
        index = client.indexes('idx')
        result = index.search(@criteria)
        unless result["results"].nil?
          res = result["results"]
          begin
            res.each do |rs|
              begin
                lnk = Link.find(:first,:conditions => "id = #{rs["docid"].to_s}")
                unless lnk.nil?
                  @links.push(lnk)
                end
              end
            end
          rescue
          end
        end
      end
      @links = @links[noOfLinksSkipCount.to_i,noOfLinksperPage.to_i]
    end
    
    unless params[:pageindex].nil?
       render :index, :layout => false
    else
       render :index
    end
    
  end

  def tagfilter

    begin
      tag = params[:tag]
      noOfLinksperPage = ENV['NoOfLinksPerPage']
      noOfLinksSkipCount = 0
      unless params[:pageindex].nil?
        noOfLinksSkipCount = noOfLinksperPage.to_i * params[:pageindex].to_i
      end
      @links = []
      unless tag.nil?
        tags = Tag.where("lower(name) = '#{tag.to_s.downcase}'")
        if(tags.count() > 0)
          tagid =tags[0].id
          # searching with the tag id
          result = Link.limit(noOfLinksperPage).offset(noOfLinksSkipCount).find(:all, :conditions => "tag_id = '#{tagid}'")
          result.each do |res|
            @links.push(res)
          end
        end
      end
    end
    unless params[:pageindex].nil?
       render :index, :layout => false
    else
       render :index
    end
  end

  def sendnotification
    delivernotifications
    render :text => "success"
  end

  def new
    @link = Link.new
    render :layout => false 
  end

  def edit
    unless params[:id].nil?
      @link = Link.find_by_id(params[:id])
      if @link.nil?
        redirect_to error_url
      end
    else
      redirect_to error_url
    end
  end

  def create

    unless params[:link].nil?
      @link = Link.new(params[:link])
      newtag = params[:newtag]
      tag = Tag.find(:first,:conditions => "name = '#{newtag}'")
      if tag.nil?
        tag = Tag.new
        tag.name = newtag
        tag.save
      end
      @link.tag_id = tag.id
      @link.user_id = current_user.id
      @link.group_id=session[:group]
      if @link.save
        #delivernotifications
        render :text => "success"
      else
        render :text => @link.errors.full_messages[0]
      end
    else
      redirect_to :action => "index"
    end
    
  end

  def quickentry
    @status = ""
    url = params[:url]
    userbookmarkletkey = params[:key]
    tagname = 'unknown'
    unless url.nil? and userbookmarkletkey.nil?
      user = User.find(:first, :conditions => "bookmarkletcode = '#{userbookmarkletkey}'")
      unless user.nil?
        link = Link.new
        link.link = url
        link.title = params[:title]
        tag = Tag.find(:first, :conditions => "name = '#{tagname}'")
        if tag.nil?
          tag = Tag.new
          tag.name = tagname
          tag.save
        end
        link.tag_id = tag.id
        link.user_id = user.id
        link.group_id = user.group_id
        unless link.save
          #puts link.errors.full_messages
          #@status = "Oops! This Blendmark already exists."
          @status = "Oops! " + link.errors.full_messages[0].to_s
        else
          #delivernotifications
          @status = "success"
        end
      else
        @status = "Oops! unable to add Blendmark due to invalid user token value passed."
      end
    else
      @status = "Oops! unable to add Blendmark due to invalid token values passed."
    end
    render :layout => false
  end

  def addtag
    @tag = Tag.new
    @tag.name = params[:name]
    @tag.description = params[:description]
    @tag.name
    if @tag.save
      render :text => "success#" + @tag.id.to_s
    else
      render :text => "Oops! something wrong happened!"
    end
    #redirect_to :action => "index"
  end

  def update
    unless params[:id].nil?
      unless params[:link].nil?
        @link = Link.find(params[:id])
        if @link.update_attributes(params[:link])
          render :text => "Link was successfully updated."
        else
          redirect_to :controller => "links", :action => "index"
        end
      else
        redirect_to :controller => "links", :action => "index"
      end
    else
      redirect_to :controller => "links", :action => "index"
    end
  end

  def destroy
    unless params[:id].nil?
      @link = Link.find_by_id(params[:id])
      unless @link.nil?
        @link.destroy
        render :text => "success"
      else
        render :text => "invalid parameter passed."
      end
    else
      render :text => "invalid parameter passed."
    end
  end

  def readlinksfrommail
    unless params[:plain].nil?
      unless params[:subject].nil?
        message = params[:plain] #Mail.new(params[:message])
        #urls = message.subject.to_s.scan(/(?:http|https):\/\/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix) #message.subject.to_s.split(/\s+/).find_all {|u| u=/^https?:/}
        urls = message.to_s.scan(/(?:http|https):\/\/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix)
        message = saveurls(urls,message)
        urls = message.to_s.scan(/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix)
        saveurls(urls,message)
        message = params[:subject]
        #urls =  message.body.to_s.scan(/(?:http|https):\/\/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix)  #message.body.to_s.split(/\s+/).find_all {|u| u=/^https?:/}
        urls =  message.to_s.scan(/(?:http|https):\/\/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix)
        message = saveurls(urls,message)
        urls = message.to_s.scan(/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix)
        saveurls(urls,message)
        render :text => "success"
      else
        render :text => "invalid parameters passed."
      end
    else
      render :text => "invalid parameters passed."
    end
  end

  def tagautocomplete
    unless params[:query].nil?
      query = params[:query]
      result = {}
      result[:query] = query
      suggestions = []
      Tag.where("lower(name) like '#{query}%'").each do |tag|
        suggestions.push(tag.name)
      end
      result[:suggestions] = suggestions
      result[:data] = []
      render :json => result
    else
      render :text => "invalid parameter passed."
    end
  end

  private
  def delivernotifications
    if(ENV['RAILS_ENV'].to_s != "development")
      Notificationlink.all.each do |link|
        #User.find(:all, :conditions => "isnotificationsubscribed = true").each do |user|
        User.all.each do |user|
          UserMailer.deliver_linknotification(link,user,current_user,Group.find(:first,:conditions => "id = '#{session[:group]}'").title)
        end
        link.destroy
      end
    end
  end
  def saveurls(urls,originalmessage)
    urls.each do |url|
      link = Link.new
      link.link = url
      link.description = "Received from mail"
      link.tag_id = 1
      link.save
      begin
        originalmessage = originalmessage.sub(url,'')
      rescue
      end
    end
    return originalmessage
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/index.html.erb
    <div id="main" role="main" >
    <% if @links.count() > 0 -%>
        <% @links.each do |link|%>
            <ul class="link">
                <li>
                    <a href="<%= link.link %>"><%= link.title %></a>
                    <ul class="sub-menu">
                        <li>Added by <a href="#" class="submitter-link"><%= User.find(link.user_id).email %></a> on <%= link.created_at.strftime("%d %M %Y") %></li>
                        <li>|</li>
                        <li><a href="#" class="comment-link">0 Comments</a></li>
                    </ul>
                </li>
                <li>
                  <div class="tags">
                    <%= link_to Tag.find(link.tag_id).name, "/tag/" + Tag.find(link.tag_id).name %>
                  </div>
                </li>
            </ul>
        <% end %>
    <% end %>
    </div>

app/views/links/new.html.erb
<!--- body -->
<div class="add-link-form">
    <%= form_for(@link) do |f| -%>
        <div class="clearfix errorbox">
        </div>
        <label>Title</label>
        <%= f.text_field :title, :id => "txttitle", :class => "small" -%>
        <label>Link</label>
        <%= f.text_field :link, :id => "txtlink", :class => "small", :value => session[:id] -%>
        <% session[:id] = nil -%>
        <label>Description</label>
        <%= f.text_area :description,:class => "small",:id =>"txtdescription",:rows => "0" -%>
        <label>Tag</label>
        <input type="text" class="small" name="newtag" id="txttag">
        <a href="#" id="addlink" class="css3-button">Save link</a>
    <% end -%>
</div>
<%= render :partial => "layouts/exceptionhub" %>
<%= stylesheet_link_tag "style_auto_complete" %>
<%= javascript_include_tag "jquery-1.4.4.min" %>
<%= javascript_include_tag "jquery.autocomplete" %>
<%= javascript_include_tag "JQValidation" %>
<script type="text/javascript" language="JavaScript">
    $(function () {
       try
       {
        var options = { 'serviceUrl' :'../autocomplete' };
        $('#txttag').autocomplete(options);
       }catch(e) {
       }
   });
</script>

app/views/links/quickentry.html.erb
<%= @status %>

app/views/links/unused.html.erb
<!--

<div class="report-container-2by3">
    <h1><span class="menu-button"> <a href="#" class="small blue gradient-button">Search</a></span></h1>
  </div>
  <div class="report-container-2by3">
        <div class="filter-container" <% if flash[:filter] == false %> style="display:none" <% end %> >
            <form action="/links/search" method="post" id="searchform">
                <label>Keyword</label>
                <input type="text" name="pattern" class="text-field" <% if flash[:filter] == true %> value="<%= @pattern %>" <% end %> />
                <label>Tag</label>
                <select name="tag" class="text-field" id="searchtag">
                     <option value="0">All</option>
                     <% Tag.find(:all).each do |tag| %>
                     <option value="<%= tag.id %>" <% if flash[:filter] == true and @tagsearch == tag.id %> selected = "true" <% end %> ><%= tag.name %></option>
                    <% end %>
                </select>
                <a href="#" class="small blue gradient-button" id="FilterSubmitButton">Search</a>
            </form>
        </div>
  </div>



  <table id="TblAddnewlink">
        <tr>
            <td>
                 <%= link_to 'Add new link', new_link_path, :id => "LnkAddnewlink" %>
            </td>
        </tr>
    </table>

   <table id="TblAddnewtag">
        <tr>
            <td>
                <%= link_to 'Add new tag', "#", :id => "LnkAddnewtag" %>
            </td>
        </tr>
    </table>


  <li><br /> <a href="#" class="small blue gradient-button" id="FilterSubmitButton">Search</a></li>

  $('.menu-button a').unbind('click');
    $('.menu-button a').click(function() {
        $('.filter-container').slideToggle(300);
    });


  // For tooltip
    $('body').append('<div class="tooltip" id="tooltip"></div>');
    $('#tooltip').hide();
    $('table.data th').mouseenter(function(e) {
        if($(this).attr('tooltip') != "")
        {
            $('#tooltip').html($(this).attr('tooltip'));
            $('#tooltip').css ({
                top: e.pageY + 5,
                left: e.pageX + 5
            }).fadeIn(100);
        }
    }).mouseleave(function() {
        $('#tooltip').hide();
    }).mousemove(function(e){
           $('#tooltip').css ({
            top: e.pageY + 5,
            left: e.pageX + 5
        });
    });


  // For Search Box
    $('#FilterSubmitButton').click(function() {
        $('#searchform').submit();
    });



  // For select listbox tag selection for search
    $('#searchtag').change(function(){
        if ($('#searchtag :selected').text() != "All" )
        {
            $('#Txthiddentagsearch').val($('#searchtag :selected').text());
        }
        else
        {
            $('#Txthiddentagsearch').val('');
        }
        $('#Txthiddentagsearch').keyup();
    });


  $("#txtsearchcriteria").bind('keyup',function(){
        $('#searchtag')[0][0].selected = true;
    });

    // For tag filter
    $('#Txthiddentagsearch').quicksearch(".linkrow", {
        noResults: '#noresultsrow',
        stripeRows: ['odd', 'even'],
        loader: 'span.loading'
    });



  <div class="tbladdtagform">
      <div class="data-entry-form">
        <form method="post" action="/addtag">
          <div class="clearfix errorbox">

          </div>
          <ol>
            <li>
              <label for="txttag"><%= image_tag "expanded.gif",:class => "collapsable", :tag => "expand" %>Tag</label>
            </li>
            <li>
              <input type="text" name="name" id="txttag" class="text-field" />
            </li>
            <li>
              <label for="field_3"><%= image_tag "collapsed.gif",:class => "collapsable", :tag => "collapse" %>Description</label>
              <textarea rows="" cols="" class="text-field" id="txtdescription"></textarea>
            </li>
            <li>
              <input type="button" class="submit" value="Add Tag" />
              <span>or <a href="#" id ="lnktagcancel">Cancel</a></span>
            </li>
          </ol>
        </form>
      </div>
    </div>




  <span class="menu-button"><div class="addnewlinkholder"><%= link_to 'Add new link', "#", :id => "lnkaddnewlink" %></div> <div class="addnewtagholder"><%= link_to 'Add new tag', "#", :id => "lnkaddnewtag" %></div></span>




  // For Adding new link
    $('.tbladdlinkform').hide();
    $('#lnkaddnewlink').click(function() {
       $('#tooltip').hide();
       $('#lnkaddnewlink').hide();
       $('#lnkaddnewtag').show();
       $('.tbladdlinkform').slideDown(500);
       $('.tbladdtagform').slideUp(500);
       setTimeout(function() { $('#tbladdlinkform input[type="text"]').eq(0).focus()},500);
    });

    $('#lnkcancel').click(function() {
        $('.tbladdlinkform').slideUp(500);
        $('#lnkaddnewlink').show();
    });

    // For Adding new tag
    $('.tbladdtagform').hide();
    $('#lnkaddnewtag').click(function() {
        $('#tooltip').hide();
        $('#lnkaddnewtag').hide();
        $('#lnkaddnewlink').show();
        $('.tbladdlinkform').slideUp(500);
        $('.tbladdtagform').slideDown(500);
        setTimeout(function() { $('#tbladdtagform input[type="text"]').eq(0).focus()},500);
    });
    $('#lnktagcancel').click(function() {
        $('.tbladdtagform').slideUp(500);
        $('#lnkaddnewtag').show();
    });



  // for adding tag
    $('#tbladdtagform input[type="button"]').click(function() {
        var tag = $('#txttag')[0].value;
        tag = $.trim(tag);
        var This = $(this);
        var errorBox  = $('#tbladdtagform .errorbox');
        if(tag!= "")
        {
            var arrayindex = $.inArray(tag,tagArray);
            if (arrayindex == -1)
            {
                $.ajax({
                    url: "/addtag",
                    timeout: 10000,
                    //datatype: 'xml',
                    cache: false,
                    data: $('#tbladdtagform form').serialize(),
                    type: "POST",
                    //contentType: "application/xml; charset=utf-8",
                    beforeSend: function() {
                        This.val("Adding......")
                    },
                    success: function(data) {
                        if (typeof (data) == typeof (int)) {
                            showError(errorBox,"Unable to reach the server. Check your interner connection. Refresh the page to continue.");
                        }
                        else if(data.indexOf("success") > -1) {
                            var splitstrings = data.split('#');
                            showError(errorBox,"Tag added successfully.");
                            tagArray.push(tag);
                            debugger;
                            if (splitstrings.length > 0)
                            {
                                $('select').append('<option value=' + splitstrings[1] + ">" + tag + "</option>")
                            }
                            setTimeout(function() {$('#lnktagcancel').trigger('click');},1000);
                        }
                        else
                        {
                            showError(errorBox,data);
                        }
                        This.val("Add link");
                    },
                    error: function(request, error) {
                        showError(errorBox,"Unable to reach the server. Refresh the page to continue.");
                        This.val("Add link");
                    }});
            }
            else
            {
                $('#txttag').focus();
                showError(errorBox,"The tag already exists, try new one.");
            }
        }
        else
        {
            $('#txttag').focus();
            showError(errorBox,"Please input tag");
        }
    });





  // For Collapse and Expands
    $('textarea').hide();
    $('.select-tag-field-div').hide();
    $('.text-tag-field-div').hide();

    $('.collapsable').click(function () {
        if ($(this).attr('tag') == "collapse")
        {
            $(this)[0].src = '/images/expanded.gif';
            $(this).attr('tag','expand');
            $(this).parents('li').find('.text-field').slideDown(100);
        }
        else
        {
            $(this)[0].src = '/images/collapsed.gif';
            $(this).attr('tag','collapse');
            $(this).parents('li').find('.text-field').slideUp(100);
        }
    });

    $('.tag-collapsable').click(function() {
         if ($(this).attr('tag') == "collapse")
        {
            $(this)[0].src = '/images/expanded.gif';
            $(this).attr('tag','expand');
            $('.select-tag-field-div').slideDown(100);
            $('.text-tag-field-div').slideDown(100);
        }
        else
        {
            $(this)[0].src = '/images/collapsed.gif';
            $(this).attr('tag','collapse');
            $('.select-tag-field-div').slideUp(100);
            $('.text-tag-field-div').slideUp(100);
        }
    });


  <%= image_tag "expanded.gif",:class => "collapsable", :tag => "expand" %>

  <%= image_tag "collapsed.gif",:class => "collapsable", :tag => "collapse" %>

  <%= image_tag "collapsed.gif",:class => "tag-collapsable", :tag => "collapse" %>



   var headerdiv = $('#div-tableheader');
    var divheaderheight = headerdiv.height();
    var headertop = headerdiv.position().top;
    // for keeping staticheader
    $(window).scroll(function() {
            var position = $(this).scrollTop();
            if (position > headertop) {
                  // headerdiv.css({'top': (position- headertop).toString() + "px"});
            }
            else
            {
                //headerdiv.css({'top': "0px"});
            }

    });


  // for keeping staticheader
    $(window).scroll(function() {
        var position = $(this).scrollTop();
        if (position > headertop) {
            headerdiv.stop().animate({
                'top': (position- headertop).toString() + "px"
            },'fast');
        }
        else {
            headerdiv.stop().animate({
                'top': "0px"
            },'fast');
        }
    });


    -->