config/routes.rb
BlendMarks::Application.routes.draw do
  get "error/index"
  get "coming/index"
  match "login", :controller => "user_sessions", :action => "new"
  match "logout", :controller => "user_sessions", :action => "destroy"
  match "register", :controller => "users", :action => "new"
  match "error", :controller => "error", :action => "index"
  match 'forgotpassword', :controller => "users", :action => "forgotpassword"
  match 'resetpassword/:id', :controller => "users", :action => "resetpassword"
  match 'quickentry', :controller => "links", :action => "quickentry"
  match 'addlink', :controller => "links", :action => "create"
  match 'confirminvitation', :controller => "users", :action => "confirminvitation"
  match 'addtag', :controller => "links", :action => "addtag"
  match 'readmail', :controller => "links", :action => "readlinksfrommail"
  match 'sendnotification',:controller => "links" , :action => "sendnotification"
  match "subscribe", :controller => "coming", :action => "subscribe"
  match 'search/:criteria(/:pageindex)', :controller => "links", :action => "search"
  match '/', :controller => "links", :action => "index" , :constraints => {:subdomain => "blendmarks"}
  match '/', :controller => "coming", :action => "index"
  match 'links/index(/:pageindex)', :controller => "links", :action => "index"
  match ':controller/:action(/:id)'
  match ':controller/:action'
  match 'tag/:tag(/:pageindex)', :controller => "links", :action => "tagfilter"
  match '/autocomplete', :controller => "links", :action => "tagautocomplete"
  resources :links
  resource :users
  resources :coming
  resources :user_sessions
end

app/models/user_session.rb
class UserSession <  Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
                      before_filter "setsubdomainasgroup"

  # for login  request
  def new
    @user_session = UserSession.new
    #render :layout => "links"
  end

  # for logout
  def destroy
    @user_session = UserSession.find
    unless @user_session.nil?
      @user_session.destroy
    end
    new
    render :new
  end

  # for login  post
  def create
    unless params[:user_session].nil?
      @user_session = UserSession.new(params[:user_session])
      @user_session.remember_me = true
      if @user_session.save
        @current_user = @user_session
        flash[:notice] = 'Successfully logged in.'
        redirect_to_root
      else
        flash[:notice] = "invalid parameters passed."
        render :action => "new"
      end
    else
        flash[:notice] = "user credentials not found."
        new
        render :action => "new"
    end
  end


  private                      
  def redirect_to_root
    redirect_to :controller => "links", :action => "index"
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div id="login-box-container">
    <div id="center">
        <%= image_tag "logo.png" %>
        <div id="login-box">
        <%= form_for(@user_session,:url => "/user_sessions") do |f| %>
            <h1>Login</h1>
            <% if @user_session.errors.any? %>
                <div class="alert-error">
                    Looks like your username or password is wrong.
                </div>
            <% end %>
            <fieldset>
                <label>Email</label>
                <%= f.text_field :username, :class => "small" %>
            </fieldset>
            <fieldset>
                <label>Password</label>
                <%= f.password_field :password, :class => "small" %>
            </fieldset>
            <%= link_to 'Login', "#", :id => "BtnFormSubmit" ,:class => "css3-button" -%>
            <p class="forgot-password">Did you <%= link_to "forget your password?", :controller => "users", :action => "forgotpassword" %>or do you need to <%= link_to 'Register', register_url  -%></p>
            <div class="clearfix"></div>
        <% end %>
        </div>
    </div>
</div>